# Generated by Django 4.2.3 on 2023-09-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedigest',
            name='topic',
            field=models.ManyToManyField(blank=True, related_name='image_digest', to='digest.topics'),
        ),
        migrations.AlterField(
            model_name='linkdigest',
            name='topic',
            field=models.ManyToManyField(blank=True, related_name='link_digest', to='digest.topics'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='topic_name',
            field=models.CharField(choices=[('Art', 'AR'), ('Sport', 'SP'), ('Computer Science', 'CS'), ('Math', 'MTH'), ('News', 'NW'), ('Education', 'ED'), ('Food', 'FD'), ('Travelling', 'TRV'), ('Animals', 'AN'), ('Memes', 'MS'), ('Technologies', 'TCH'), ('Music', 'MSC'), ('Cinema', 'CN')], max_length=30, unique=True),
        ),
    ]
